//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Core_User
    {
        public string ID { get; set; }
        public string CompoentID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string UserPYM { get; set; }
        public string UserPWD { get; set; }
        public bool UserSex { get; set; }
        public string UserNickname { get; set; }
    }
}
